#!/bin/bash

VERSION="1.0.0"

# Function: show help message
show_help() {
    cat << EOF
Usage: dbash 

Launch an interactive shell into a running Docker container selected via fzf.

Options:
  -h, --help    Show this help message and exit.

Examples:
  dbash           # Uses bash by default
  dbash --help    # Displays this help message
  dbash --version # Show version and exit
EOF
}

# Version
if [[ "$1" == "--version" || "$1" == "-v" ]]; then
    echo "$(basename "$0") version $VERSION"
    exit 0
fi

# Help
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    show_help
    exit 0
fi

# Chack for fzf
if ! command -v fzf &> /dev/null; then
    echo "fzf not found, please check the README at https://github.com/wrestlingcarbonapple/dbash" 
    exit 1
fi

# List running containers with name and image
containers=$(docker ps --format "{{.ID}} {{.Image}} {{.Names}}")

# Check if there are any running containers
if [ -z "$containers" ]; then
    echo "No running containers."
    exit 0
fi

# Headers
headers="CONTAINER_ID IMAGE NAME"
containers_with_headers=$(echo -e "$containers\n$headers" | column -t)

# Use fzf to select a container
selected=$(echo "$containers_with_headers" | fzf --prompt="Select container: ")

# Exit if nothing selected
[ -z "$selected" ] && exit 0

# Extract container ID from selected line
container_id=$(echo "$selected" | awk '{print $1}')

selected_shell=$(docker exec "$container_id" cat /etc/shells | awk '{print $1}'| sed 1d | sort | fzf --header="SHELL" --prompt='Select shell>')

# Exit if nothing selected
[ -z "$selected_shell" ] && exit 0

# Exec into the container
echo "Executing $selected_shell in container $container_id..."
docker exec -it "$container_id" "$selected_shell" 
